swagger: "2.0"
info:
  title: "NestAI API"
  description: "API Gateway"
  version: "1.0.0"
host: "api.nestaiframework.com"
schemes:
  - https
paths:
  /check-agent/{agentName}:
    get:
      summary: "Check if an agent exists"
      operationId: "checkAgent"
      parameters:
        - name: "agentName"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "Success"
        "403":
          description: "Forbidden"
      x-google-backend:
        address: "https://api.nestaiframework.com"

  /store-agent:
    post:
      summary: "Store agent details"
      operationId: "storeAgent"
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            type: "object"
            properties:
              agentName:
                type: "string"
              agentDetails:
                type: "object"
      responses:
        "200":
          description: "Success"
        "403":
          description: "Forbidden"
      x-google-backend:
        address: "https://api.nestaiframework.com"
